/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include <stdio.h>
#include "stm32f4xx.h"


void blink();
void timer_delay() ;

int main(void)
{
	RCC->AHB1ENR |= 1<<3 ; //GPIOD CLK enable
	GPIOD->MODER = 1<<24 ;   // 12*2
	GPIOD->OSPEEDR = 00 ;
	GPIOD->PUPDR = 00 ;

	RCC->AHB1ENR |= 1<<0 ; //GPIOA CLK enable
	GPIOA->MODER |= 0<<0 ;   // input mode
	//GPIOA->OSPEEDR = 00 ;   // low speed
	GPIOA->PUPDR |= 0x10<<0 ;    //pull down

	EXTI->FTSR |= 1<<0 ;  //falling trigger
	SYSCFG->EXTICR[0] |= 0x0<0 ;   //pa0 exti line selected
	EXTI->IMR |= 1<<0 ;  // enable exti


	NVIC_PR->IP[EXTI0_IRQn] |= ( 0x5<<4 ) ;  // priority set
	*NVIC_ISER0 |= ( 1 << EXTI0_IRQn );   // interrupt enable
	while(1) ;
}


void EXTI0_IRQHandler(void)
{
	blink() ;
	if(EXTI->PR & ( 1 << 0))
		{
			//clear
			EXTI->PR |= ( 1 << 0);
		}

}

void blink()
{
	GPIOD->ODR  ^=  ( 1<<12 );    // led toggle
	timer_delay() ;
	GPIOD->ODR ^=  (1<<12)  ;
	timer_delay() ;
	GPIOD->ODR ^=  (1<<12)  ;
	timer_delay() ;
	GPIOD->ODR ^=  (1<<12)  ;
	timer_delay() ;

}

void timer_delay()
{
	RCC->APB1ENR |= 1<<0 ; //TIM2 CLK EN
	TIM2->CR1 = 0x00 ;  // reset
	TIM2->PSC = 256 ;  // 16bit wide
	TIM2->ARR = 0x0000FFFF ; // tim2 32bit wide
	TIM2->CR1 |= 1<<0 ;  // enable
	while(TIM2->CNT != 0x0000FFFF) ;
	TIM2->CR1 = 0<<0 ; // disable timer
	TIM2->CNT = 0x0 ;
}

